#include <cinnabar-render/types.hpp>

#include <GL/glew.h>

const ce::BufferBit
	ce::COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT,
	ce::DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT,
	ce::STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT;

const ce::DepthFunc
	ce::DEPTH_NEVER = GL_NEVER,
	ce::DEPTH_LESS = GL_LESS,
	ce::DEPTH_EQUAL = GL_EQUAL,
	ce::DEPTH_LEQUAL = GL_LEQUAL,
	ce::DEPTH_GREATER = GL_GREATER,
	ce::DEPTH_NOTEQUAL = GL_NOTEQUAL,
	ce::DEPTH_GEQUAL = GL_GEQUAL,
	ce::DEPTH_ALWAYS = GL_ALWAYS;

const ce::Datatype
	TYPE_BYTE = GL_BYTE,
	TYPE_UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
	TYPE_SHORT = GL_SHORT,
	TYPE_UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
	TYPE_INT = GL_INT,
	TYPE_UNSIGNED_INT = GL_UNSIGNED_INT,

	TYPE_HALF_FLOAT = GL_HALF_FLOAT,
	TYPE_FLOAT = GL_FLOAT,
	TYPE_DOUBLE = GL_DOUBLE,

	TYPE_FIXED = GL_FIXED,

	TYPE_INT_2_10_10_10_REV = GL_INT_2_10_10_10_REV,
	TYPE_UNSIGNED_INT_10F_11F_11F_REV = GL_UNSIGNED_INT_10F_11F_11F_REV,

	TYPE_UNSIGNED_BYTE_3_3_2 = GL_UNSIGNED_BYTE_3_3_2,
	TYPE_UNSIGNED_BYTE_2_3_3_REV = GL_UNSIGNED_BYTE_2_3_3_REV,
	TYPE_UNSIGNED_SHORT_5_6_5 = GL_UNSIGNED_SHORT_5_6_5,
	TYPE_UNSIGNED_SHORT_5_6_5_REV = GL_UNSIGNED_SHORT_5_6_5_REV,
	TYPE_UNSIGNED_SHORT_4_4_4_4 = GL_UNSIGNED_SHORT_4_4_4_4,
	TYPE_UNSIGNED_SHORT_4_4_4_4_REV = GL_UNSIGNED_SHORT_4_4_4_4_REV,
	TYPE_UNSIGNED_SHORT_5_5_5_1 = GL_UNSIGNED_SHORT_5_5_5_1,
	TYPE_UNSIGNED_SHORT_1_5_5_5_REV = GL_UNSIGNED_SHORT_1_5_5_5_REV,
	TYPE_UNSIGNED_INT_8_8_8_8 = GL_UNSIGNED_INT_8_8_8_8,
	TYPE_UNSIGNED_INT_8_8_8_8_REV = GL_UNSIGNED_INT_8_8_8_8_REV,
	TYPE_UNSIGNED_INT_10_10_10_2 = GL_UNSIGNED_INT_10_10_10_2,
	TYPE_UNSIGNED_INT_2_10_10_10_REV = GL_UNSIGNED_INT_2_10_10_10_REV;

const ce::TextureTarget
	TARGET_TEXTURE_2D = GL_TEXTURE_2D,
	TARGET_PROXY_TEXTURE_2D = GL_PROXY_TEXTURE_2D,
	TARGET_TEXTURE_1D_ARRAY = GL_TEXTURE_1D_ARRAY,
	TARGET_PROXY_TEXTURE_1D_ARRAY = GL_PROXY_TEXTURE_1D_ARRAY,
	TARGET_TEXTURE_RECTANGLE = GL_TEXTURE_RECTANGLE,
	TARGET_PROXY_TEXTURE_RECTANGLE = GL_PROXY_TEXTURE_RECTANGLE,
	TARGET_TEXTURE_CUBE_MAP_POSITIVE_X = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
	TARGET_TEXTURE_CUBE_MAP_NEGATIVE_X = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
	TARGET_TEXTURE_CUBE_MAP_POSITIVE_Y = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
	TARGET_TEXTURE_CUBE_MAP_NEGATIVE_Y = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
	TARGET_TEXTURE_CUBE_MAP_POSITIVE_Z = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
	TARGET_TEXTURE_CUBE_MAP_NEGATIVE_Z = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z,
	TARGET_PROXY_TEXTURE_CUBE_MAP = GL_PROXY_TEXTURE_CUBE_MAP;

const ce::ColorSpace
	COLORSPACE_NONE = 0, // TODO: is there a better value for this? GL_NONE exists but doesn't seem correct

	COLORSPACE_RED = GL_RED,
	COLORSPACE_RG = GL_RG,
	COLORSPACE_RGB = GL_RGB,
	COLORSPACE_BGR = GL_BGR,
	COLORSPACE_RGBA = GL_RGBA,
	COLORSPACE_BGRA = GL_BGRA,

	COLORSPACE_RED_INTEGER = GL_RED_INTEGER,
	COLORSPACE_RG_INTEGER = GL_RG_INTEGER,
	COLORSPACE_RGB_INTEGER = GL_RGB_INTEGER,
	COLORSPACE_BGR_INTEGER = GL_BGR_INTEGER,
	COLORSPACE_RGBA_INTEGER = GL_RGBA_INTEGER,
	COLORSPACE_BGRA_INTEGER = GL_BGRA_INTEGER,

	COLORSPACE_STENCIL_INDEX = GL_STENCIL_INDEX,
	COLORSPACE_DEPTH_COMPONENT = GL_DEPTH_COMPONENT,
	COLORSPACE_DEPTH_STENCIL = GL_DEPTH_STENCIL;

const ce::TextureFormat
	TEXTUREFORMAT_NONE = 0, // TODO: is there a better value for this? GL_NONE exists but doesn't seem correct

	TEXTUREFORMAT_RED = GL_RED,
	TEXTUREFORMAT_RG = GL_RG,
	TEXTUREFORMAT_RGB = GL_RGB,
	TEXTUREFORMAT_RGBA = GL_RGBA,
	TEXTUREFORMAT_DEPTH_COMPONENT = GL_DEPTH_COMPONENT,
	TEXTUREFORMAT_DEPTH_STENCIL = GL_DEPTH_STENCIL,

	TEXTUREFORMAT_R8 = GL_R8,
	TEXTUREFORMAT_R8_SNORM = GL_R8_SNORM,
	TEXTUREFORMAT_R16F = GL_R16F,
	TEXTUREFORMAT_R32F = GL_R32F,
	TEXTUREFORMAT_R8UI = GL_R8UI,
	TEXTUREFORMAT_R8I = GL_R8I,
	TEXTUREFORMAT_R16UI = GL_R16UI,
	TEXTUREFORMAT_R16I = GL_R16I,
	TEXTUREFORMAT_R32UI = GL_R32UI,
	TEXTUREFORMAT_R32I = GL_R32I,
	TEXTUREFORMAT_RG8 = GL_RG8,
	TEXTUREFORMAT_RG8_SNORM = GL_RG8_SNORM,
	TEXTUREFORMAT_RG16F = GL_RG16F,
	TEXTUREFORMAT_RG32F = GL_RG32F,
	TEXTUREFORMAT_RG8UI = GL_RG8UI,
	TEXTUREFORMAT_RG8I = GL_RG8I,
	TEXTUREFORMAT_RG16UI = GL_RG16UI,
	TEXTUREFORMAT_RG16I = GL_RG16I,
	TEXTUREFORMAT_RG32UI = GL_RG32UI,
	TEXTUREFORMAT_RG32I = GL_RG32I,
	TEXTUREFORMAT_RGB8 = GL_RGB8,
	TEXTUREFORMAT_SRGB8 = GL_SRGB8,
	TEXTUREFORMAT_RGB565 = GL_RGB565,
	TEXTUREFORMAT_RGB8_SNORM = GL_RGB8_SNORM,
	TEXTUREFORMAT_R11F_G11F_B10F = GL_R11F_G11F_B10F,
	TEXTUREFORMAT_RGB9_E5 = GL_RGB9_E5,
	TEXTUREFORMAT_RGB16F = GL_RGB16F,
	TEXTUREFORMAT_RGB32F = GL_RGB32F,
	TEXTUREFORMAT_RGB8UI = GL_RGB8UI,
	TEXTUREFORMAT_RGB8I = GL_RGB8I,
	TEXTUREFORMAT_RGB16UI = GL_RGB16UI,
	TEXTUREFORMAT_RGB16I = GL_RGB16I,
	TEXTUREFORMAT_RGB32UI = GL_RGB32UI,
	TEXTUREFORMAT_RGB32I = GL_RGB32I,
	TEXTUREFORMAT_RGBA8 = GL_RGBA8,
	TEXTUREFORMAT_SRGB8_ALPHA8 = GL_SRGB8_ALPHA8,
	TEXTUREFORMAT_RGBA8_SNORM = GL_RGBA8_SNORM,
	TEXTUREFORMAT_RGB5_A1 = GL_RGB5_A1,
	TEXTUREFORMAT_RGBA4 = GL_RGBA4,
	TEXTUREFORMAT_RGB10_A2 = GL_RGB10_A2,
	TEXTUREFORMAT_RGBA16F = GL_RGBA16F,
	TEXTUREFORMAT_RGBA32F = GL_RGBA32F,
	TEXTUREFORMAT_RGBA8UI = GL_RGBA8UI,
	TEXTUREFORMAT_RGBA8I = GL_RGBA8I,
	TEXTUREFORMAT_RGB10_A2UI = GL_RGB10_A2UI,
	TEXTUREFORMAT_RGBA16UI = GL_RGBA16UI,
	TEXTUREFORMAT_RGBA16I = GL_RGBA16I,
	TEXTUREFORMAT_RGBA32I = GL_RGBA32I,
	TEXTUREFORMAT_RGBA32UI = GL_RGBA32UI,

	TEXTUREFORMAT_DEPTH_COMPONENT16 = GL_DEPTH_COMPONENT16,
	TEXTUREFORMAT_DEPTH_COMPONENT24 = GL_DEPTH_COMPONENT24,
	TEXTUREFORMAT_DEPTH_COMPONENT32F = GL_DEPTH_COMPONENT32F,
	TEXTUREFORMAT_DEPTH24_STENCIL8 = GL_DEPTH24_STENCIL8,
	TEXTUREFORMAT_DEPTH32F_STENCIL8 = GL_DEPTH32F_STENCIL8;

const ce::MeshFormat
	MESHFORMAT_POINTS = GL_POINTS,
	MESHFORMAT_LINE_STRIP = GL_LINE_STRIP,
	MESHFORMAT_LINE_LOOP = GL_LINE_LOOP,
	MESHFORMAT_LINES = GL_LINES,
	MESHFORMAT_LINE_STRIP_ADJACENCY = GL_LINE_STRIP_ADJACENCY,
	MESHFORMAT_LINES_ADJACENCY = GL_LINES_ADJACENCY,
	MESHFORMAT_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
	MESHFORMAT_TRIANGLE_FAN = GL_TRIANGLE_FAN,
	MESHFORMAT_TRIANGLES = GL_TRIANGLES,
	MESHFORMAT_TRIANGLE_STRIP_ADJACENCY = GL_TRIANGLE_STRIP_ADJACENCY,
	MESHFORMAT_TRIANGLES_ADJACENCY = GL_TRIANGLES_ADJACENCY,
	MESHFORMAT_PATCHES = GL_PATCHES;