name: Packaging
on:
  push:
    branches: [feature/gh-actions]
  workflow_dispatch:
jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - run: ./packaging/create-deb.sh
        shell: bash
        uses: cinnabar-engine/cinnabar@feature/gh-actions
