name: Unit Testing
on:
  push:
    branches: [develop]
  pull_request:
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install build-essential cmake libglfw3-dev libglew-dev libglm-dev -y
          chmod +x github-scripts/debian.sh

      - name: Configure
        run: |
          github-scripts/debian.sh configure

      - name: Build
        run: |
          github-scripts/debian.sh build

  Arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo docker build -f packaging/arch.dockerfile -t ce-arch .
          sudo docker run -it -d --name ce-arch-test -v "$(pwd)":/app:rw ce-arch
          sudo docker exec ce-arch-test chmod +x /app/github-scripts/arch.sh

      - name: Configure
        run: |
          sudo docker exec ce-arch-test /app/github-scripts/arch.sh configure

      - name: Build
        run: |
          sudo docker exec ce-arch-test /app/github-scripts/arch.sh build

      - name: Clean Up
        run: |
          sudo docker stop ce-arch-test
          sudo docker rm ce-arch-test -f
          sudo docker rmi ce-arch -f
  Windows:
    runs-on: windows-latest
    env:
      GLEW_PATH: C:\lib\glew-2.2.0\bin
      GLM_ROOT_DIR: C:\lib\glm
      GLFW_ROOT: C:\lib\glfw-3.3.4
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - run: choco install wget unzip 7zip -y
      - name: Install Dependencies
        env:
          GLEW_DOWNLOAD: https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip
          GLM_DOWNLOAD: https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
          GLFW_DOWNLOAD: https://github.com/glfw/glfw/releases/download/3.3.4/glfw-3.3.4.zip
        run: |
          mkdir c:/lib
          wget -O glew.zip $env:GLEW_DOWNLOAD
          wget -O glfw3.zip $env:GLFW_DOWNLOAD
          wget -O glm.zip $env:GLM_DOWNLOAD

          unzip glew.zip -d c:\lib
          unzip glfw3.zip -d c:\lib
          unzip glm.zip -d c:\lib

      - name: Configure
        run: |
          $env:Path += ";$env:GLEW_PATH"

          echo $env:PATH

          github-scripts\windows.bat configure

      - name: Build
        run: |
          github-scripts\windows.bat build
