name: Unit Testing
on: [push, pull_request]
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install build-essential cmake libsdl2-dev libglew-dev libglm-dev libassimp-dev -y
          chmod +x tests/debian.sh

      - name: Configure
        run: |
          tests/debian.sh configure
      - name: Build
        run: |
          tests/debian.sh build

      - name: Package
        run: |
          tests/debian.sh package
  Arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo docker build -f arch.dockerfile -t ce-arch .
          sudo docker run -it -d --name ce-arch-test ce-arch
          sudo docker exec ce-arch-test chmod +x /app/tests/arch.sh

      - name: Configure
        run: |
          sudo docker exec ce-arch-test /app/tests/arch.sh configure

      - name: Build
        run: |
          sudo docker exec ce-arch-test /app/tests/arch.sh build

      - name: Package
        run: |
          sudo docker exec ce-arch-test /app/tests/arch.sh package

      - name: Clean Up
        run: |
          sudo docker stop ce-arch-test
          sudo docker rm ce-arch-test -f
          sudo docker rmi ce-arch -f
  Windows:
    runs-on: windows-latest
    env:
      GLEW_DOWNLOAD: https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - run: choco install wget unzip -y
      - name: Install Dependencies
        run: |
          mkdir c:/lib
          wget -O glew.zip $env:GLEW_DOWNLOAD

          unzip glew.zip -d c:\lib

          set "PATH=%PATH%;C:\lib\glew-2.1.0\bin"

          # vcpkg integrate install
          # vcpkg install sdl2 glew glm
          # # :: Install-Package sdl2 -Force
          # # :: Install-Package glew -Force
          # # # Install-Package glm -Force


      - name: Configure
        run: |
          tests\windows.bat configure
      - name: Build
        run: |
          tests\windows.bat build

      - name: Package
        run: |
          tests\windows.bat package
