name: Unit Testing
on:
  push:
    branches: [develop]
  pull_request:
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install build-essential cmake libsdl2-dev libglew-dev libglm-dev libassimp-dev -y
          chmod +x github-scripts/debian.sh

      - name: Configure
        run: |
          github-scripts/debian.sh configure

      - name: Build
        run: |
          github-scripts/debian.sh builds

      - name: Package
        run: |
          github-scripts/debian.sh package
  Arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Install Dependencies
        run: |
          sudo docker build -f packaging/arch.dockerfile -t ce-arch .
          sudo docker run -it -d --name ce-arch-test ce-arch
          sudo docker exec ce-arch-test chmod +x /app/github-scripts/arch.sh

      - name: Configure
        run: |
          sudo docker exec ce-arch-test /app/github-scripts/arch.sh configure

      - name: Build
        run: |
          sudo docker exec ce-arch-test /app/github-scripts/arch.sh build

      - name: Package
        run: |
          sudo docker exec ce-arch-test /app/github-scripts/arch.sh package

      - name: Clean Up
        run: |
          sudo docker stop ce-arch-test
          sudo docker rm ce-arch-test -f
          sudo docker rmi ce-arch -f
  Windows:
    runs-on: windows-latest
    env:
      GLEW_PATH: C:\lib\glew-2.2.0\bin
      SDL2DIR: C:\lib\SDL2-2.0.16
      GLM_ROOT_DIR: C:\lib\glm
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - run: choco install wget unzip 7zip -y
      - name: Install Dependencies
        env:
          GLEW_DOWNLOAD: https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0-win32.zip
          GLM_DOWNLOAD: https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
          SDL2_DOWNLOAD: https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip
        run: |
          mkdir c:/lib
          wget -O glew.zip $env:GLEW_DOWNLOAD
          wget -O sdl2.zip $env:SDL2_DOWNLOAD
          wget -O glm.zip $env:GLM_DOWNLOAD

          unzip glew.zip -d c:\lib
          unzip sdl2.zip -d c:\lib
          unzip glm.zip -d c:\lib

          # vcpkg integrate install
          # vcpkg install sdl2 glew glm
          # # :: Install-Package sdl2 -Force
          # # :: Install-Package glew -Force
          # # # Install-Package glm -Force

      - name: Configure
        run: |
          $env:Path += ";$env:GLEW_PATH"

          echo $env:PATH

          github-scripts\windows.bat configure
      - name: Build
        run: |
          github-scripts\windows.bat build

      - name: Package
        run: |
          github-scripts\windows.bat package
