name: Unit Testing
on: push
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependacies
        run: sudo apt install build-essential cmake libsdl2-dev libglew-dev libglm-dev libassimp-dev
      # Checkout the branch
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: Configure
        run: |
          tests/debian.sh configure
      - name: Build
        run: |
          tests/debian.sh build

      - name: Packaging
        run: |
          tests/debian.sh package
  Arch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
      - name: Install Dependacies
        run: |
          sudo docker build -f arch.dockerfile . -t ce-arch
          sudo docker run ce-arch

      - name: Configure
        run: |
          sudo docker run ce-arch cd /app
          sudo docker run ce-arch mkdir build
          sudo docker run ce-arch cd build
          sudo docker run ce-arch cmake ..

      - name: Build
        run: |
          sudo docker run ce-arch cd /app
          sudo docker run ce-arch cmake --build ./build
